import { createSlice } from "@reduxjs/toolkit";

export const languageSlice = createSlice({
  name: "language",
  initialState: {
    words: {
      en: {
        set_language: "FRENCH",
        sample: "SAMPLE",
        clear_all: "CLEAR ALL",
        pdf: "PDF",
        live_edit: "LIVE EDIT",
        import: "IMPORT",
        export: "EXPORT",
        primary: "Primary",
        secondary: "Secondary",
        title: "Main Title",
        subtitle: "Subtitle",
        titles: "Titles",
        textLeft: "Text 1",
        textRight: "Text 2",
        color_hint: "* double click the color for the default color",
        add: "ADD",
        clear: "CLEAR",
        personal_information: "Personal Information",
        social: "Social",
        languages: "Languages",
        hobbies: "Hobbies",
        education: "Education",
        experience: "Experience",
        skills: "Skills",
        projects: "Projects",
        courses: "Courses",
        references: "References",
        social_upper: "SOCIAL",
        languages_upper: "LANGUAGES",
        hobbies_upper: "HOBBIES",
        education_upper: "EDUCATION",
        experience_upper: "EXPERIENCE",
        skills_upper: "SKILLS",
        projects_upper: "PROJECTS",
        courses_upper: "COURSES",
        references_upper: "REFERENCES",
        name_surname: "Name Surname",
        form_title: "Title",
        photo: "Photo",
        address: "Address",
        phone_number: "Phone Number",
        email_address: "Email Address",
        about: "About",
        twitter_username: "Twitter Username",
        github_username: "Github Username",
        linkedin_username: "LinkedIn Username",
        personal_website: "Personal Website",
        external_url: "External URL",
        username_or_url: "Username or URL Address",
        select: "Select",
        language: "Language Name",
        native: "Native Language",
        hobby: "Hobby Name",
        school: "School Name",
        subject: "Subject",
        degree: "Degree",
        city: "City",
        from: "From",
        to: "To",
        company: "Company Name",
        position: "Position",
        description: "Description",
        skill: "Skill Name",
        level: "Level",
        project: "Project Name",
        link: "Project Link",
        course: "Course Name",
        reference: "Reference Name",
        reference_title: "Reference Title",
        confirm: "Are you sure all data will be deleted?",
        top: "Top",
        right: "Right",
        bottom: "Bottom",
        left: "Left",
        margin_hint: "* you can set print page margins",
      },
      fr: {
        set_language: "ENGLISH",
        sample: "EXEMPLE",
        clear_all: "TOUT EFFACER",
        pdf: "PDF",
        live_edit: "ÉDITION EN DIRECT",
        import: "IMPORTER",
        export: "EXPORTER",
        primary: "Primaire",
        secondary: "Secondaire",
        title: "Titre Principal",
        subtitle: "Sous-titre",
        titles: "Titres",
        textLeft: "Texte 1",
        textRight: "Texte 2",
        color_hint: "* double-cliquez sur la couleur pour la couleur par défaut",
        add: "AJOUTER",
        clear: "EFFACER",
        personal_information: "Informations Personnelles",
        social: "Réseaux Sociaux",
        languages: "Langues",
        hobbies: "Loisirs",
        education: "Formation",
        experience: "Expérience",
        skills: "Compétences",
        projects: "Projets",
        courses: "Formations",
        references: "Références",
        social_upper: "RÉSEAUX SOCIAUX",
        languages_upper: "LANGUES",
        hobbies_upper: "LOISIRS",
        education_upper: "FORMATION",
        experience_upper: "EXPÉRIENCE",
        skills_upper: "COMPÉTENCES",
        projects_upper: "PROJETS",
        courses_upper: "FORMATIONS",
        references_upper: "RÉFÉRENCES",
        name_surname: "Nom Prénom",
        form_title: "Titre",
        photo: "Photo",
        address: "Adresse",
        phone_number: "Numéro de Téléphone",
        email_address: "Adresse Email",
        about: "À Propos",
        twitter_username: "Nom d'utilisateur Twitter",
        github_username: "Nom d'utilisateur GitHub",
        linkedin_username: "Nom d'utilisateur LinkedIn",
        personal_website: "Site Web Personnel",
        external_url: "URL Externe",
        username_or_url: "Nom d'utilisateur ou URL",
        select: "Sélectionner",
        language: "Langue",
        native: "Langue Maternelle",
        hobby: "Loisir",
        school: "École",
        subject: "Domaine d'Étude",
        degree: "Diplôme",
        city: "Ville",
        from: "De",
        to: "À",
        company: "Entreprise",
        position: "Poste",
        description: "Description",
        skill: "Compétence",
        level: "Niveau",
        project: "Nom du Projet",
        link: "Lien du Projet",
        course: "Nom de la Formation",
        reference: "Nom de la Référence",
        reference_title: "Titre de la Référence",
        confirm: "Êtes-vous sûr de vouloir supprimer toutes les données ?",
        top: "Haut",
        right: "Droite",
        bottom: "Bas",
        left: "Gauche",
        margin_hint: "* vous pouvez définir les marges de la page d'impression",
      },
    },
    language: "en",
  },
  reducers: {
    setLanguage: (state, action) => {
      state.language = action.payload;
    },
  },
});

export const { setLanguage } = languageSlice.actions;

export default languageSlice.reducer;
